language: cpp
sudo: false
dist: xenial

compiler:
- clang
- gcc

addons:
  postgresql: "9.5"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - bison
    - clang-8
    - cpp-7
    - flex
    - gcc-7
    - g++-7
    - libpq-dev
    - libpq5
    - libstdc++-7-dev
    - libtool
    - llvm-8
    - pkg-config
    - clang-format-8
    - perl
    - parallel
    - gdb
    - libunwind-dev

before_script:
  - ulimit -c unlimited -S

script: ./ci-build.sh

after_failure:
  - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1)
  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" ./src/stellar-core -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

cache:
  directories:
  - $HOME/.ccache

notifications:
  email: false
  slack:
    secure: VYA87p8f6PgmOhL8b8DM4t6k8vPYjULpT7LBhvmNBNe8iiNDtTzLpRbUXg6t6Ij7Y3MU4uOJ5K617hCqs81VfRoOakbiYTWHeYSsMmIrUM4+d5MZM4pVP0/bCE49qt06bZINorh6IHChhfuvod3uyUqbgNrwRf/qDIIboFDIty8=

branches:
 only:
 - auto

stages:
  - compile
  - test

matrix:
  fast_finish: true
  include:
    - stage: compile
      compiler: clang
      script: ./ci-build.sh --disable-tests
    - stage: compile
      compiler: gcc
      script: ./ci-build.sh --disable-tests

